name = "lookcrafted-api"
main = "src/index.ts"
compatibility_date = "2025-05-04"
minify = true
workers_dev = false
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://lookcrafted.com,https://www.lookcrafted.com"
BETTER_AUTH_URL = "https://api.lookcrafted.com"
FRONTEND_URL = "https://lookcrafted.com"
POLAR_SERVER = "production"
POLAR_STARTER_PRODUCT_ID = "28045a52-86db-42c0-a546-ae3820ff955c"
POLAR_BASIC_PRODUCT_ID = "2e1e0573-c602-4fe5-b094-6080c7c69753"
POLAR_PREMIUM_PRODUCT_ID = "5cc4cb32-0e55-4e5e-9dee-85a237f57778"