name = "lookcrafted-api"
main = "src/index.ts"
compatibility_date = "2025-05-04"
minify = true
workers_dev = false
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://lookcrafted.com,https://www.lookcrafted.com"
BETTER_AUTH_URL = "https://api.lookcrafted.com"
FRONTEND_URL = "https://lookcrafted.com"
CREEM_STARTER_PRODUCT_ID = "prod_3hADxaiZBibg2SG01UVBjE"
CREEM_BASIC_PRODUCT_ID = "prod_7SMPOao8jCBYV9WA12kF0Y"
CREEM_PREMIUM_PRODUCT_ID = "prod_1q4ArjLlmBtcQb8y59cqby"